services:
  db:
    image: postgres:15-alpine
    container_name: chat-db
    restart: always
    environment:
      POSTGRES_USER: chatuser
      POSTGRES_PASSWORD: chatpassword
      POSTGRES_DB: chatdb
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: chat-redis
    restart: always
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: chat-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
      - "61613:61613"
    command: sh -c "rabbitmq-plugins enable --offline rabbitmq_stomp; rabbitmq-server"

  kafka:
    image: apache/kafka:3.7.0
    container_name: chat-kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:29092,CONTROLLER://0.0.0.0:9093,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: chat-backend
    restart: always
    ports:
      - "8082:8082"
    depends_on:
      - db
      - rabbitmq
      - kafka
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/chatdb
      - SPRING_DATASOURCE_USERNAME=chatuser
      - SPRING_DATASOURCE_PASSWORD=chatpassword
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_FLYWAY_ENABLED=false
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:29092
      - APP_RABBITMQ_HOST=rabbitmq
      - SPRING_REDIS_HOST=redis

volumes:
  pgdata: