spring.application.name=chat
server.port=8082

spring.datasource.url=jdbc:postgresql://localhost:5432/chatdb
spring.datasource.username=chatuser
spring.datasource.password=chatpassword
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.flyway.enabled=false

spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
spring.kafka.consumer.group-id=chat-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JacksonJsonSerializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JacksonJsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=*

app.rabbitmq.host=${APP_RABBITMQ_HOST:localhost}

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=kelvengomes123321@gmail.com
spring.mail.password=nlyzhtrgalsacbnx
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


spring.data.redis.host=${SPRING_REDIS_HOST:localhost}
spring.data.redis.port=6379
spring.cache.type=redis
spring.cache.redis.time-to-live=600000
spring.cache.redis.cache-null-values=false